### ISSUE TITLE
Make selfhostable with runtime environment variable substitution

### ISSUE THREAD

**Issue by redmushie** [Shock-Link/WebUI#50]
Found an excellent guide: https://moreillon.medium.com/environment-variables-for-containerized-vue-js-applications-f0aa943cb962

Will put this into practice tomorrow.

**Comment by LucHeart** [comment]
as I said before,already doing that, see webpack js

**Comment by redmushie** [comment]
I looked at the webpack.config.js but I don't see anything w.r.t. variable substitution at _runtime_, only compile time.

I did see this: https://github.com/Shock-Link/WebUI/blob/0c498c0e30f8d4d4644faa3e35b151069bb48b49/webpack.config.js#L86-L91

But that's also compile time:
> The DefinePlugin replaces variables in your code with other values or expressions **at compile time**. This can be useful for allowing different behavior between development builds and production builds

If there's something else I'm missing I'm all ears!

**Comment by LucHeart** [comment]
yes, but it should just be that, but you do it in main.js

**Comment by LucHeart** [comment]
nevermind, you cannot get anything at runtime, since it doesnt have a runtime, its just statically built files.

**Comment by redmushie** [comment]
Yeah exactly. The trick is to grab the container env vars on startup, substitute them in the *.js files, and _then_ start serving files. Should be easy :)
